---
- hosts: jenkins-master
  become: yes
  tasks:
    - name: Stop jenkins
      service:
        name: jenkins
        state: stopped

    - name: uninstall jenkins
      apt:
        name: jenkins 
        state: absent
        purge: yes
...
