---
- hosts: jenkins-master
  become: yes
  tasks:
    - name: stop jenkins
      service:
        name: jenkins
        state: stopped

    - name: uninstall jenkins
      apt:
        name: jenkins 
        state: absent
        purge: yes

    - name: remove sources
      file: /etc/apt/sources.list.d/jenkins.list
      state: absent
...
