---
- name: Include vars | Include OS Specific Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include Task | Include OS Specific Tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Include Task | Configure Jenkins
  include_tasks: config.yml

- name: Include Task | Install Plugins
  include_tasks: plugin.yml

- name: Systemd | restart jenkins
  systemd:
    name: jenkins
    state: restarted
...
