---
- name: Include Vars | Include Plugins list
  include_vars: plugins.yml

- name: File | Create Plugin Directory
  file:
    path: "{{ jenkins_home}}/plugins"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: File | Create Updates Directory
  file:
    path: "{{ jenkins_home}}/updates"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Jenkins Plugin | Install Jenkins plugins using password.
  jenkins_plugin:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    jenkins_home: "{{ jenkins_home }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}"
    state: present
    updates_url: "{{ jenkins_updates_url }}"
    with_dependencies: yes
    validate_certs: no
    force: yes
  with_items: "{{ my_jenkins_plugins }}"
  register: plugin_result
  until: plugin_result is success
  retries: 3
  delay: 2
  notify: restart jenkins
...
