---
- name: Get URL | Install Jenkins Repo
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
    validate_certs: no

- name: RPM Key | Add Jenkins repo GPG key.
  rpm_key:
    key: "{{ jenkins_repo_key_url }}"
    state: present
    validate_certs: no

- name: Get URL | Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    validate_certs: no
  when: jenkins_version is defined

- name: Stat | Check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
  register: specific_version

- name: Yum | Install specific version of Jenkins.
  yum:
    name: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    state: present
  when: jenkins_version is defined and specific_version.stat.exists

- name: Package | Ensure Jenkins is installed.
  package:
    name: jenkins
    state: present

- name: systemd | Start Jenkins and also issue daemon-reload to pick up config changes
  systemd:
    name: jenkins
    state: started
    daemon_reload: yes
...
