---
#jenkins_master_url: "http://192.168.43.195:8080/"
#jenkins_master_url: "http:/192.168.43.25:8080/"
jenkins_master_host: "{{ hostvars['unix_node1']['ansible_host'] }}"
jenkins_master_port: 8080
jenkins_master_url: "http://{{ jenkins_master_host }}:{{ jenkins_master_port }}"
jenkins_master_username: admin
jenkins_master_api_token: "{{ dev_vault_jenkins_admin_password }}"      # Do not encrypt it as it's being used in systemd service ExecStart Unit


jenkins_plugin_url: "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins"
jenkins_swarm_client_version: 3.28
jenkins_swarm_client_jar_url: "{{ jenkins_plugin_url }}/swarm-client/{{ jenkins_swarm_client_version }}/swarm-client-{{ jenkins_swarm_client_version }}.jar"
jenkins_swarm_client_service_name: jenkins_swarm_client.service

no_of_retries: 3
no_of_executors: 2

...
