---
jenkins_master_url: "http://vikas-VirtualBox:8080/"
jenkins_master_username: admin
jenkins_master_api_token: '118ba3769a985df083e20c569ff326dd29'


jenkins_plugin_url: "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins"
jenkins_swarm_client_version: 3.28
jenkins_swarm_client_jar_url: "{{ jenkins_plugin_url }}/swarm-client/{{ jenkins_swarm_client_version }}/swarm-client-{{ jenkins_swarm_client_version }}.jar"
jenkins_swarm_client_service_name: jenkins_swarm_client.service

no_of_retries: 3
no_of_executors: 2

...
