---
jenkins_version: 2.317  #  Use `latest` to get latest availavle version.

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_home: /var/lib/jenkins
jenkins_init_groovy_d: "{{ jenkins_home }}/init.groovy.d"

jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_port: "{{ jenkins_http_port }}"
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_connection_retries: 10
jenkins_connection_delay: 5

# basic-security.groovy
jenkins_admin_username: admin
jenkins_admin_password: "{{ dev_vault_jenkins_admin_password }}"
jenkins_admin_password_file: ""

# jenkins.j2
jenkins_java_opts: "-Djenkins.install.runSetupWizard=false"
jenkins_java_args: "--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT"

# Other params
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

# If Jenkins is behind a proxy, configure this.
jenkins_proxy_host: ""
jenkins_proxy_port: ""
jenkins_proxy_noproxy:
  - "127.0.0.1"
  - "localhost"
...
