---
- name: Apt | Install java package
  apt:
    name: "{{ java_packages }}"
    state: present

# Environment setup
- name: Template | Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home

...
