---
jenkins_slave_user_name: jenkins
jenkins_slave_user_password: "{{ dev_vault_jenkins_slave_user_password | password_hash('sha512') }}"

jenkins_slave_user_group: "{{ jenkins_slave_user_name }}"
jenkins_slave_user_groups: ''       # Additional Jekins user groups

jenkins_slave_name: jenkins-{{ ansible_os_family }}-agent
jenkins_slave_label: win10e1
jenkins_slave_dir: C:\Users\{{ jenkins_slave_user_name }}\agent

jenkins_swarm_run_args: -jar {{ jenkins_slave_dir }}\swarm-client-{{ jenkins_swarm_client_version }}.jar -name {{ jenkins_slave_name}} -fsroot {{ jenkins_slave_dir }} -username {{jenkins_master_username}} -password {{ jenkins_master_api_token }} -master {{ jenkins_master_url }} -labels {{ jenkins_slave_label }} -executors {{ no_of_executors}} -disableSslVerification -retry {{ no_of_retries}}

java_exe: C:\Program Files\Java\jdk1.8.0_211\bin\java.exe
java_home: C:\Program Files\Java\jdk1.8.0_211\bin

winsw_home: C:\Program Files\WinSW\bin
jenkins_slave_winsw_app: jenkins_swarm_client
jenkins_slave_winsw_exe: C:\Program Files\WinSW\bin\{{ jenkins_slave_winsw_app }}.exe
jenkins_slave_winsw_xml: C:\Program Files\WinSW\bin\{{ jenkins_slave_winsw_app}}.xml
...
