---
- name: User | Create User
  win_user:
    name: "{{ jenkins_slave_user_name }}"
    description: Created for Jenkins Swarm Client
    password: "{{ jenkins_slave_user_password }}"
    password_never_expires: yes
    state: present
    groups: "{{ jenkins_slave_user_groups }}"

- name: User Rights | Add account to Log on as a service. # This is required to run the service as jenkins user
  win_user_right:
    name: SeServiceLogonRight
    users:
    - "{{ jenkins_slave_user_name }}"
    action: add

- name: File | Create Jenkins Agent Folder
  win_file:
    path: "{{ jenkins_slave_dir }}"
    state: directory

- name: Owner | Change owner of the folder - Jenkins Agent
  win_owner:
    path: "{{ jenkins_slave_dir }}"
    user: "{{ jenkins_slave_user_name }}"
    recurse: yes

- name: Get URL | Download Swarm Client
  win_get_url:
    url: "{{ jenkins_swarm_client_jar_url }}"
    dest: "{{ jenkins_slave_dir }}"

- name: File | Create WinSW home path
  win_file:
    path: "{{ winsw_home }}"
    state: directory

- name: Copy | Copy WinSW executable (Windows Service Wrapper)
  win_copy:
    src: files/winsw.exe
    dest: "{{ jenkins_slave_winsw_exe }}"

- name: Copy | Copy service config file
  win_template:
    src: jenkins_swarm_client.xml.j2
    dest: "{{ jenkins_slave_winsw_xml }}"

- name: Command | Stop the service
  win_command: "{{ jenkins_slave_winsw_app }} stop"
  args:
    chdir: "{{ winsw_home }}"
  ignore_errors: True

- name: Command | Uninstall the Service using winsw
  win_command: "{{ jenkins_slave_winsw_app }} uninstall"
  args:
    chdir: "{{ winsw_home }}"
  ignore_errors: True

- name: Command | Install the Service using winsw
  win_command: "{{ jenkins_slave_winsw_app }} install"
  args:
    chdir: "{{ winsw_home }}"

- name: Command | Start the Service using winsw
  win_command: "{{ jenkins_slave_winsw_app }} start"
  args:
    chdir: "{{ winsw_home }}"

#- name: NSSM | Install the jenkins-swarm-client service
#  win_nssm:
#    name: "{{ jenkins_swarm_client_service_name }}"
#    description: Jenkins swarm client to connect to Jenkins Master
#    application: "{{ java_exe }}"
#    arguments: "{{ jenkins_swarm_run_args }}"
#
#- name: Service | Configure and start the jenkins-swarm-client service
#  win_service:
#    name: "{{ jenkins_swarm_client_service_name }}"
#    description: Jenkins swarm client to connect to Jenkins Master
#    username: "{{ jenkins_slave_user_name }}"
#    password: "{{ jenkins_slave_user_password }}"
#    path: "{{ java_exe }}"
#    start_mode: auto
#    state: started
#  async: 180
#  poll: 0
...
